version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum update -y
      - yum install -y mesa-libgbm libXtst libX11 libXcomposite libXcursor libXi libXrandr libXScrnSaver libXrender libxshmfence
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run cy:parallel

